# DevOps pipeline for Azure cloud deployment

trigger: none
#  batch: false
#  branches:
#    include:
#      - master

variables:
  - group: product-readiness.docfx
  - name: gitRepoName
    value: Countries
  - name: gitOwner
    value: pyueh-osi

jobs:
  - job: Publish
    pool:
      # name: 00-OSIManaged-Containers
      # demands: AgentType -equals osimanagedagent
      vmImage: 'vs2017-win2016'
    steps:
      - script: |
          choco install DocFX --version=2.56.2
        displayName: 'Install DocFX 2.56.2'
      - script: |
          choco install wkhtmltopdf --version=0.12.5
        displayName: 'Install wkhtmltopdf 0.12.5'

      - script: |
          echo.
          dir
          echo.
          echo.
          echo "*** Clone source ***"
          echo.
          mkdir source
          cd source
          git clone -b master https://user:$(gitToken)@github.com/$(gitOwner)/$(gitRepoName).git --recurse-submodules
          dir
          cd $(gitRepoName)\docfx_project
          dir
          echo.
          echo "*** Build DocFx site ***"
          echo.
          docfx.exe build ./docfx.json
          echo.
          echo "*** Build PDF ***"
          echo.
          docfx.exe pdf ./docfx.json
          copy _site_pdf\*.pdf _site
          echo.
          echo "*** Contents of _site ***"
          echo.
          dir "C:\source\$(gitRepoName)\docfx_project\_site"
          echo.
          echo "Complete"
          echo.
        workingDirectory: 'C:\'
        displayName: 'Publish DocFX'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'C:\source\$(gitRepoName)\docfx_project\_site'
          ArtifactName: 'drop'
          publishLocation: 'Container'

      - task: AzureCLI@2
        inputs:
          azureSubscription: 'PYueh-Visual Studio Enterprise Subscription(94e67d6d-a3e6-425f-b9af-16971682c94c)'
          scriptType: 'ps'
          scriptLocation: 'inlineScript'
          inlineScript: 'az storage blob delete-batch --source "`$web" --account-name "petersandbox1" --pattern "en/$(gitRepoName)/*"'

      - task: AzureFileCopy@4
        inputs:
          # SourcePath: '$(Build.ArtifactStagingDirectory)'
          SourcePath: 'C:\source\$(gitRepoName)\docfx_project\_site\**'
          azureSubscription: 'PYueh-Visual Studio Enterprise Subscription(94e67d6d-a3e6-425f-b9af-16971682c94c)'
          Destination: 'AzureBlob'
          storage: 'petersandbox1'
          ContainerName: '$web'
          BlobPrefix: 'en/$(gitRepoName)'
